### ISSUE TITLE
Solves the console error but causes a new issue

### ISSUE THREAD

**Issue by hitec4ever** [rynaldos/woocommerce-js-cookie-fix#2]
This plugin will solve the console error but on the checkout page it generates the issue that WooCommerce will show both billing details and shipping detail fields instead of only billing details with the option to choose to send it to a different address.

**Comment by ontiuk** [comment]
Problem is that the original cookie js file was jquery based and for Woocommerce 3.0+ it's vanilla javascript. They didn't bother to think it would cause issues!

Still, the wp_register_script relies on jquery, so the 3rd param was array( 'jquery' ). 

Plugin author here has mistakenly changed that to array( 'js' ). Bue as there is no 'js' handle registsted the new cookie file doesn't get enqueued and loaded.

Line in wooommerce-js-cookie-fix.php needs changing to:

wp_register_script( 'js-cookie', plugins_url( 'js_cookie' . $suffix . '.js', __FILE__ ), array( ), '2.1.4', true );

i.e.  change array('js') to array()

Billing checkbox works ok now.

**Comment by ontiuk** [comment]
Try changing  array( 'js' ) to array() in the plugin file wp_register_script function. It's creating a dependency that is invalid. The old cookie file was jquery based and so had array('jquery'). The new WC3+ file is vanilla js and so no dependency.

Clear your browser cache after. Sorted it for me. The 'js' was stopping the cookie file loading, and also the cart-fragments.min.js file which may use it as a dependency.
